name = "Create Aeronautics"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcdae13519aa04f94a57c0e2f8d2b59aae770f6e66e096bf5b8befe1060380f4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
