name = "Create Aeronautics"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89b0b1e0f20b9488ca40f592b8d4e320ff1dad589a58c91836101dccf98d3620"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
